// Returns OSM road polylines around a coordinate.
// Prefers the prebuilt bundle at /streets.json (generated by
// scripts/fetch-streets.mjs); falls back to live Overpass only if a
// requested key is missing from the bundle.

type Polyline = [number, number][];
type Bundle = Record<string, Polyline[]>;

const BUNDLE_RADIUS = 1800;

let bundlePromise: Promise<Bundle> | null = null;
const cache = new Map<string, Promise<Polyline[]>>();

const OVERPASS = "https://overpass-api.de/api/interpreter";

function loadBundle(): Promise<Bundle> {
	if (!bundlePromise) {
		bundlePromise = fetch(`${import.meta.env.BASE_URL}streets.json`)
			.then((r) => (r.ok ? (r.json() as Promise<Bundle>) : ({} as Bundle)))
			.catch(() => ({}) as Bundle);
	}
	return bundlePromise;
}

function key(lat: number, lng: number, radiusMeters: number): string {
	return `${lat.toFixed(4)},${lng.toFixed(4)},${radiusMeters}`;
}

async function fetchOverpass(
	lat: number,
	lng: number,
	radiusMeters: number,
): Promise<Polyline[]> {
	const q = `[out:json][timeout:12];
		way["highway"~"^(motorway|trunk|primary|secondary|tertiary|residential|unclassified|service)$"]
			(around:${radiusMeters},${lat},${lng});
		out geom;`;
	const res = await fetch(OVERPASS, {
		method: "POST",
		headers: { "Content-Type": "application/x-www-form-urlencoded" },
		body: `data=${encodeURIComponent(q)}`,
	});
	if (!res.ok) throw new Error(`overpass ${res.status}`);
	const json = (await res.json()) as {
		elements: { geometry?: { lat: number; lon: number }[] }[];
	};
	const lines: Polyline[] = [];
	for (const el of json.elements) {
		if (!el.geometry) continue;
		const pts: Polyline = el.geometry.map((p) => [p.lat, p.lon]);
		if (pts.length >= 2) lines.push(pts);
	}
	return lines;
}

export function getCityStreets(
	lat: number,
	lng: number,
	radiusMeters: number = BUNDLE_RADIUS,
): Promise<Polyline[]> {
	const k = key(lat, lng, radiusMeters);
	const hit = cache.get(k);
	if (hit) return hit;

	const p = (async () => {
		if (radiusMeters === BUNDLE_RADIUS) {
			const bundle = await loadBundle();
			if (bundle[k]) return bundle[k];
		}
		return fetchOverpass(lat, lng, radiusMeters);
	})().catch((err) => {
		cache.delete(k);
		throw err;
	});

	cache.set(k, p);
	return p;
}
